CREATE TABLE IF NOT EXISTS Users
(
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT UNIQUE,
    Email TEXT UNIQUE,
    Password TEXT UNIQUE,
    -- RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);
	
CREATE TABLE IF NOT EXISTS Posts 
(
    PostID INTEGER PRIMARY KEY,
    UserID INTEGER,
    Username TEXT,
    Title TEXT,
    Body TEXT,
    Likes INTEGER,
    Dislikes INTEGER,
    Comments TEXT,
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Comments
(
    CommentID INTEGER PRIMARY KEY,
    Username TEXT NOT NULL,
    PostID INTEGER NOT NULL,
    Body TEXT NOT NULL,
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Categories
(
    CategoryID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Description TEXT
);

CREATE TABLE Likes
(
    LikeID INTEGER PRIMARY KEY,
    UserID INTEGER,
    PostID INTEGER,
    CommentID INTEGER
);

CREATE TABLE Dislikes
(
    DislikeID INTEGER PRIMARY KEY,
    UserID INTEGER,
    PostID INTEGER,
    CommentID INTEGER
);

CREATE TABLE Cookies
(
    SessionID TEXT NULL,
    UserID TEXT NOT NULL,
    CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);